<?php
/**
 * @package Deyan
 * @author Angel Gabriel
 * @web http://angelgabriel.tk
 * @mail angel.wrt@gmail.com
 *
 * @iconlib gray
 * 
 * This file is required by iconlib's admin page, to echo the icon's menu, 
 * you can register here all the icons in your library wich will be presented as a menu
 * in the icon settings admin page.
*/ 

	
		//register icons
		deyan_icons_menu(array(	'edit-square',
					'edit-rounded',
					'idea',
		                        'applications',
		                        'bookmarks',
		                        'bookmarks-alt',
		                        'calculator',
		                        'camera',
		                        'chart-alt',
		                        'clock',
		                        'laptop',
		                        'plugin',
		                        'user',
		                        'cd',
		                        'sheet',
		                        'sheet-folder',
		                        'downloads',
		                        'mail',
		                        'world',
		                        'desktop',
		                        'favorites-folder',
		                        'favorites',
		                        'folder',
		                        'games',
		                        'gear',
		                        'edit-rounded-file',
		                        'edit-square-file',
		                        'chart-rounded',
		                        'hard-drive',
		                        'headphones',
		                        'home',
		                        'gadget',
		                        'chat',
		                        'music',
		                        'light',
		                        'lighting',
		                        'lock',
		                        'play-alt',
		                        'play',
		                        'memory',
		                        'mouse',
		                        'friends',
		                        'music-alt',
		                        'music-folder',
		                        'mute',
		                        'laptop-alt',
		                        'hard-drive-alt',
		                        'notepad-alt',
		                        'notepad',
		                        'oh',
		                        'paint',
		                        'paint-alt',
		                        'user-alt',
		                        'camera-alt',
		                        'camera-folder',
		                        'monitor-folder',
		                        'logout',
		                        'proyector-alt',
		                        'proyector',
		                        'trash-empty',
		                        'trash',
		                        'rss-alt',
		                        'rss',
		                        'scanner',
		                        'crop',
		                        'search-folder',
		                        'search',
		                        'settings-folder',
		                        'photos-alt',
		                        'photos',
		                        'sound-alt',
		                        'sound',
		                        'nosound',
		                        'chart',
		                        'monitor',
		                        'monitor-alt',
		                        'apps',
		                        'twitter',
		                        'wireless',
		                        'movie-alt',
		                        'tv',
		                        'video-alt',
		                        'video',
		                        'movie-folder',
		                        'movie',
		                        'phone',
		                        'phone-alt',
		                        'world-alt',
		                        'file',
		                        'settings',
		                        'edit-alt',
		                        'edit',
		                        'close',
		                        'zip',
		                        ));